name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clone BPB Worker Panel
        run: |
          git clone --depth=1 https://github.com/bia-pain-bache/BPB-Worker-Panel.git bpb-temp

      - name: Install dependencies and build
        run: |
          cd bpb-temp
          npm install
          npm run build

      - name: Copy built worker
        run: |
          cp bpb-temp/_worker.js ./_worker.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
